### ISSUE TITLE
(question) what if u don't do the api key step

### ISSUE THREAD

**Issue by krispyking24** [TimShaw1/Among-Us-AI#1]
what would happen and or what hat would break if u didn't do it would it just be the part where the bot talks to the other players in the meetings also idk if u wanted questions or anything on ur github sorry if u didn't

**Comment by TimShaw1** [comment]
Without an API key, the bot is unable to chat in meetings. The ChatGPT.py script would throw an error, and odds are you'd need to restart the main script after each meeting.

**Comment by krispyking24** [comment]
hmm maybe if it detects no api key then tell the player that they need to be the one talking but the rest is handled by the bot/script
