### ISSUE TITLE
im new i dont understand help it says: No such file or directory: 'E:\\SteamLibrary\\steamapps\\common\\Among Us\\sendData.txt

### ISSUE THREAD

**Issue by Idk65555** [TimShaw1/Among-Us-AI#12]

**Comment by NikoFromOneshot** [comment]
The bot is currently non-functional as the project's creator has other things to do.

**Comment by Un1dent1f1ed** [comment]
@TimShaw1 Do you know if this will be updated

**Comment by TimShaw1** [comment]
I don't have any plans to update the bot at the moment
