### ISSUE TITLE
Question about the AmongUsMenu

### ISSUE THREAD

**Issue by sdmhans** [TimShaw1/Among-Us-AI#3]
I have watched your tutorial about this project on Youtube: https://www.youtube.com/watch?v=VF41pxxw9uw&ab_channel=TimShaw. You mentioned that you used the AmongUsMenu for reading game memory. I notice that the BepInEx constantly writes files(sendData.txt, chatData.txt) under the game directory, your program needs to read them in order to make decisions. Any short descriptions or code on how BepInEx works and how we can specify the outputs? 
Thanks, great project!

**Comment by TimShaw1** [comment]
You can find more information about how I pipe data in my  [Backdoor repo](https://github.com/TimShaw1/AmongUsAI-Backdoor)
