### ISSUE TITLE
at the meeting presses buttons not where they are

### ISSUE THREAD

**Issue by y9felix** [TimShaw1/Among-Us-AI#4]
When meeting starts, the program presses slightly more left, where the actual button of the chat is, and because of this unable to write messages

**Comment by felix-yata** [comment]
nvm, I'm just too lazy to keep trying if it didn't work out the first time

**Comment by TimShaw1** [comment]
Resolved in d7d1bba83a02231aeeb9f0f99061bbf47164baf1
