### ISSUE TITLE
Getting WaitOneNoCheck Error

### ISSUE THREAD

**Issue by iskidfromAddict** [TimShaw1/Among-Us-AI#5]
Hey thanks for making this it seems awesome but when i run my game after completing the steps i get this error.

> System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
>    at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
>    at System.Threading.WaitHandle.WaitOne()
>    at Doorstop.Entrypoint.Start() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/DoorstopEntrypoint.cs:line 37

**Comment by TimShaw1** [comment]
Seems to be an issue with BepInEx. I'm not sure what could be causing it, you could try asking [https://github.com/BepInEx/BepInEx](url)
